//
//  KRWCameraButtonStyleKit.swift
//  CameraClone
//
//  Created by Konstantin Wachendorff on 10/11/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class KRWCameraButtonStyleKit : NSObject {

    //// Initialization

    override class func load() {
    }

    //// Drawing Methods

    class func drawCameraButton() {

        //// outerRing Drawing
        var outerRingPath = UIBezierPath(ovalInRect: CGRectMake(2, 2, 69.5, 68.5))
        UIColor.whiteColor().setFill()
        outerRingPath.fill()
        UIColor.darkGrayColor().setStroke()
        outerRingPath.lineWidth = 2
        outerRingPath.stroke()


        //// innerRing Drawing
        var innerRingPath = UIBezierPath()
        innerRingPath.moveToPoint(CGPointMake(55.95, 55.95))
        innerRingPath.addCurveToPoint(CGPointMake(55.95, 17.05), controlPoint1: CGPointMake(66.68, 45.21), controlPoint2: CGPointMake(66.68, 27.79))
        innerRingPath.addCurveToPoint(CGPointMake(17.05, 17.05), controlPoint1: CGPointMake(45.21, 6.32), controlPoint2: CGPointMake(27.79, 6.32))
        innerRingPath.addCurveToPoint(CGPointMake(17.05, 55.95), controlPoint1: CGPointMake(6.32, 27.79), controlPoint2: CGPointMake(6.32, 45.21))
        innerRingPath.addCurveToPoint(CGPointMake(55.95, 55.95), controlPoint1: CGPointMake(27.79, 66.68), controlPoint2: CGPointMake(45.21, 66.68))
        innerRingPath.closePath()
        UIColor.darkGrayColor().setStroke()
        innerRingPath.lineWidth = 2
        innerRingPath.stroke()
    }

    class func drawCameraButtonClicked() {

        //// outerRing Drawing
        var outerRingPath = UIBezierPath(ovalInRect: CGRectMake(2, 2, 69.5, 68.5))
        UIColor.lightGrayColor().setFill()
        outerRingPath.fill()
        UIColor.darkGrayColor().setStroke()
        outerRingPath.lineWidth = 2
        outerRingPath.stroke()


        //// innerRing Drawing
        var innerRingPath = UIBezierPath()
        innerRingPath.moveToPoint(CGPointMake(55.95, 55.95))
        innerRingPath.addCurveToPoint(CGPointMake(55.95, 17.05), controlPoint1: CGPointMake(66.68, 45.21), controlPoint2: CGPointMake(66.68, 27.79))
        innerRingPath.addCurveToPoint(CGPointMake(17.05, 17.05), controlPoint1: CGPointMake(45.21, 6.32), controlPoint2: CGPointMake(27.79, 6.32))
        innerRingPath.addCurveToPoint(CGPointMake(17.05, 55.95), controlPoint1: CGPointMake(6.32, 27.79), controlPoint2: CGPointMake(6.32, 45.21))
        innerRingPath.addCurveToPoint(CGPointMake(55.95, 55.95), controlPoint1: CGPointMake(27.79, 66.68), controlPoint2: CGPointMake(45.21, 66.68))
        innerRingPath.closePath()
        UIColor.darkGrayColor().setStroke()
        innerRingPath.lineWidth = 2
        innerRingPath.stroke()
    }

}

